In [ ]:
import polars as pl

In [2]:
# Define pathings
data_path = '../01_data/'
out_path = '../03_output/'

In [3]:
#Load data
pronouns_df = pl.read_csv(data_path + 'das_tfg_pronoun_study.csv', separator= ',' )

pronouns_df.head()

shape: (5, 3)
┌─────────────────────────────────┬──────┬─────────────────────────────────┐
│ Left                            ┆ KWIC ┆ Right                           │
│ ---                             ┆ ---  ┆ ---                             │
│ str                             ┆ str  ┆ str                             │
╞═════════════════════════════════╪══════╪═════════════════════════════════╡
│ <s> NARRATOR Yes, indeed. </s>… ┆ they ┆ are locked away, to await the … │
│ <s> NARRATOR Yes, indeed. </s>… ┆ your ┆ fate. </s><s> Only, in the anc… │
│ <s> NARRATOR Yes, indeed. </s>… ┆ it   ┆ is stated, that one day an Und… │
│ brands the Undead. </s><s> And… ┆ it   ┆ not so that thou art new. </s>… │
│ the Undead. </s><s> And in thi… ┆ thou ┆ art new. </s><s> Thou fared we… │
└─────────────────────────────────┴──────┴─────────────────────────────────┘

In [4]:
#Load Character master table
char_master_df = pl.read_csv(data_path + 'das_char_master.csv')\
                   .with_columns(pl.col('Character').str.replace(',','').alias('Character'))

char_master_df.head()

shape: (5, 3)
┌─────────────────────────────┬───────┬───────┐
│ Character                   ┆ Class ┆ Age   │
│ ---                         ┆ ---   ┆ ---   │
│ str                         ┆ str   ┆ str   │
╞═════════════════════════════╪═══════╪═══════╡
│ ALVINA OF THE DARKROOT WOOD ┆ High  ┆ Old   │
│ ANASTACIA OF ASTORA         ┆ Low   ┆ Young │
│ ANDRE OF ASTORA             ┆ Low   ┆ Old   │
│ BIG HAТ LOGAN               ┆ Low   ┆ Old   │
│ BLACKSMITH VAMOS            ┆ Low   ┆ Old   │
└─────────────────────────────┴───────┴───────┘

In [5]:
# # Function to extract the name of the speaking character from the left context.
# def name_finder(text, punctuation = [',','.',';',':','!','?']):
#     # Get rid of half sentences in the left context and from the end of sentence marker.
#     paragraphs = text.split('<s>')
#     paragraphs_full = ''.join(paragraphs[1:]).split('<s/>')
#     text = ' '.join(paragraphs_full)
#     # Remove punctuation from text.
#     for char in punctuation:
#         text = text.replace(char, '')
#     words = text.split(' ')
#     caps = []
#     # Search for words fully in uppercase that are longer than a single letter.
#     for word in words:
#         if (word == word.upper()) & (len(word) > 1):
#             caps.append(word)
#     caps = ' '.join(caps)
#     # If there are none return a null value to make forward filling easier.
#     if caps == '':
#         caps = None
#     return caps

In [6]:
# Function to extract the name of the speaking character from the left context.
def name_finder(text, punctuation = [',','.',';',':','!','?']):
    # Get rid of half sentences in the left context and from the end of sentence marker.
    paragraphs = text.split('<s>')
    paragraphs_full = ''.join(paragraphs[1:]).split('</s>')
    text = ' '.join(paragraphs_full)
    # Remove punctuation from text.
    for char in punctuation:
        text = text.replace(char, '')
    text = text.replace('\n', ' ')
    words = text.split(' ')
    caps = ['|']
    previous_was_caps = False
    # Search for words fully in uppercase that are longer than a single letter.
    for word in words:
        if (word == word.upper()) & (len(word) > 1):
            caps.append(word)
            previous_was_caps = True
            continue
        # In case there are more than one name in the captured context, select the last to appear.
        if previous_was_caps:
            caps.append('|')
            previous_was_caps = False
    # print(caps)
    if caps[-1] == '|':
        caps = caps[:-1]
    caps = ' '.join(caps)
    caps = caps.split('|')[-1].strip()
    # If there are none return a null value to make forward filling easier.
    if caps == '':
        caps = None
    return caps

In [7]:
# Extract the speaking character for each row, turn all KWIC lowercase to avoid redundant values
pronouns_df = pronouns_df.with_columns(pl.col('Left').map_elements(name_finder, return_dtype=pl.Utf8).alias('Character'))\
                         .with_columns(pl.col('KWIC').str.to_lowercase().alias('KWIC'))\
                         .with_columns(pl.col('Character').forward_fill().alias('Character'))\
                         .with_columns(pl.col('Left').str.replace_all('<s>','').str.replace_all('</s>','\n'),
                                       pl.col('Right').str.replace_all('<s>','').str.replace_all('</s>','\n'))\

pronouns_df

shape: (3_459, 4)
┌──────────────────────────────┬──────┬──────────────────────────────┬─────────────────────────────┐
│ Left                         ┆ KWIC ┆ Right                        ┆ Character                   │
│ ---                          ┆ ---  ┆ ---                          ┆ ---                         │
│ str                          ┆ str  ┆ str                          ┆ str                         │
╞══════════════════════════════╪══════╪══════════════════════════════╪═════════════════════════════╡
│  NARRATOR Yes, indeed.       ┆ they ┆ are locked away, to await    ┆ NARRATOR                    │
│  The D…                      ┆      ┆ the …                        ┆                             │
│  NARRATOR Yes, indeed.       ┆ your ┆ fate.                        ┆ NARRATOR                    │
│  The D…                      ┆      ┆  Only, in the ancient l…     ┆                             │
│  NARRATOR Yes, indeed.       ┆ it   ┆ is stated, that one day an   ┆ NARRATOR                    │
│  The D…                      ┆      ┆ Und…                         ┆                             │
│ brands the Undead.           ┆ it   ┆ not so that thou art new.    ┆ ALVINA OF THE DARKROOT WOOD │
│  And in th…                  ┆      ┆  Th…                         ┆                             │
│ the Undead.                  ┆ thou ┆ art new.                     ┆ ALVINA OF THE DARKROOT WOOD │
│  And in this land…           ┆      ┆  Thou fared well to …        ┆                             │
│ …                            ┆ …    ┆ …                            ┆ …                           │
│ You''re a persistent one,    ┆ we   ┆ meet again.                  ┆ VINCE OF THOROLUND          │
│ are…                         ┆      ┆  Vereor Nox.                 ┆                             │
│                              ┆      ┆  Eg…                         ┆                             │
│ with your kind.              ┆ you  ┆ ?                            ┆ VINCE OF THOROLUND          │
│  But there''s…               ┆      ┆  I cannot overlook a threat… ┆                             │
│ your kind.                   ┆ i    ┆ cannot overlook a threat to  ┆ VINCE OF THOROLUND          │
│  But there''s not …          ┆      ┆ M'…                          ┆                             │
│ that I can do.               ┆ i    ┆ ''ll grind you into dust!    ┆ VINCE OF THOROLUND          │
│  I am Vince of…              ┆      ┆  By…                         ┆                             │
│ do.                          ┆ you  ┆ into dust!                   ┆ VINCE OF THOROLUND          │
│  I am Vince of Thorolund.…   ┆      ┆  By the Gods... ..…          ┆                             │
└──────────────────────────────┴──────┴──────────────────────────────┴─────────────────────────────┘

In [8]:
#Add character class and age information from master table
pronouns_df = pronouns_df.join(char_master_df, on='Character', how = 'left')

pronouns_df

shape: (3_459, 6)
┌─────────────────────────┬──────┬────────────────────────┬────────────────────────┬───────┬───────┐
│ Left                    ┆ KWIC ┆ Right                  ┆ Character              ┆ Class ┆ Age   │
│ ---                     ┆ ---  ┆ ---                    ┆ ---                    ┆ ---   ┆ ---   │
│ str                     ┆ str  ┆ str                    ┆ str                    ┆ str   ┆ str   │
╞═════════════════════════╪══════╪════════════════════════╪════════════════════════╪═══════╪═══════╡
│  NARRATOR Yes, indeed.  ┆ they ┆ are locked away, to    ┆ NARRATOR               ┆ null  ┆ null  │
│  The D…                 ┆      ┆ await the …            ┆                        ┆       ┆       │
│  NARRATOR Yes, indeed.  ┆ your ┆ fate.                  ┆ NARRATOR               ┆ null  ┆ null  │
│  The D…                 ┆      ┆ Only, in the ancient   ┆                        ┆       ┆       │
│                         ┆      ┆ l…                     ┆                        ┆       ┆       │
│  NARRATOR Yes, indeed.  ┆ it   ┆ is stated, that one    ┆ NARRATOR               ┆ null  ┆ null  │
│  The D…                 ┆      ┆ day an Und…            ┆                        ┆       ┆       │
│ brands the Undead.      ┆ it   ┆ not so that thou art   ┆ ALVINA OF THE DARKROOT ┆ High  ┆ Old   │
│  And in th…             ┆      ┆ new.                   ┆ WOOD                   ┆       ┆       │
│                         ┆      ┆  Th…                   ┆                        ┆       ┆       │
│ the Undead.             ┆ thou ┆ art new.               ┆ ALVINA OF THE DARKROOT ┆ High  ┆ Old   │
│  And in this land…      ┆      ┆  Thou fared well to …  ┆ WOOD                   ┆       ┆       │
│ …                       ┆ …    ┆ …                      ┆ …                      ┆ …     ┆ …     │
│ You''re a persistent    ┆ we   ┆ meet again.            ┆ VINCE OF THOROLUND     ┆ Low   ┆ Young │
│ one, are…               ┆      ┆  Vereor Nox.           ┆                        ┆       ┆       │
│                         ┆      ┆  Eg…                   ┆                        ┆       ┆       │
│ with your kind.         ┆ you  ┆ ?                      ┆ VINCE OF THOROLUND     ┆ Low   ┆ Young │
│  But there''s…          ┆      ┆ I cannot overlook a    ┆                        ┆       ┆       │
│                         ┆      ┆ threat…                ┆                        ┆       ┆       │
│ your kind.              ┆ i    ┆ cannot overlook a      ┆ VINCE OF THOROLUND     ┆ Low   ┆ Young │
│  But there''s not …     ┆      ┆ threat to M'…          ┆                        ┆       ┆       │
│ that I can do.          ┆ i    ┆ ''ll grind you into    ┆ VINCE OF THOROLUND     ┆ Low   ┆ Young │
│  I am Vince of…         ┆      ┆ dust!                  ┆                        ┆       ┆       │
│                         ┆      ┆  By…                   ┆                        ┆       ┆       │
│ do.                     ┆ you  ┆ into dust!             ┆ VINCE OF THOROLUND     ┆ Low   ┆ Young │
│ I am Vince of           ┆      ┆  By the Gods... ..…    ┆                        ┆       ┆       │
│ Thorolund.…             ┆      ┆                        ┆                        ┆       ┆       │
└─────────────────────────┴──────┴────────────────────────┴────────────────────────┴───────┴───────┘

In [9]:
# Sanity check for extracted characters
pronouns_df.to_pandas()['Character'].unique()

array(['NARRATOR', 'ALVINA OF THE DARKROOT WOOD', 'ANASTACIA OF ASTORA',
       'ANDRE OF ASTORA', 'BIG HAТ LOGAN', 'BLACKSMITH VAMOS',
       'CRESTFALLEN MERCHANT', 'CRESTFALLEN WARRIOR',
       'CROSSBREED PRISCILLA', 'DARK SUN GWYNDOLIN', 'DARKMOON KNIGHTESS',
       'DARKSTALKER KAATHЕ', 'DOMHNALL OF ZENA', 'DUSK OF OOLACILE',
       'EINGYI OF THE GREAT SWAMP', 'ELIZABETH KEEPER OF THE SANCTUARY',
       'GIANT BLACKSMITH', 'GRIGGS OF VINHEIM',
       'GWYNEVERE PRINCESS OF SUNLIGHT', 'HAWKEYE GOUGН',
       'INGWARD KEEPER OF THE SEAL', 'KINGSEEKER FRAMPТ',
       'LAURENTIUS OF THЕ GREAT SWAMP', 'LAUTREC OF CARIM',
       "LORD''S BLADE CIARAN", 'MARVELOUS CHESTER', 'OSCAR OF ASTORA',
       'OSWALD OF CARIM', 'PETRUS OF THOROLUND', 'QUELANA OF IZALITH',
       'RHEA OF THOROLUND', 'RICKERT OF VINHEIM', 'SHIVA OF THE EAST',
       'SIEGLINDE OF CATARINA', 'SIEGMEYER OF CATARINA', 'HAWK GIRL',
       'SOLAIRE OF ASTORA', 'THE FAIR LADY', 'TRUSTY PATCHES',
       'UNDEAD MERCHANT (FEMALE)', 'UNDEAD MERCHANT (MALE)',
       'VINCE OF THOROLUND'], dtype=object)

In [10]:
# Save enriched dataframe into a csv file.
pronouns_df.write_csv(out_path + 'pronoun_analysis.csv', separator= ';')