In [1]:
import polars as pl
import pandas as pd

import sys
sys.path.append('../04_utils')

from utils import name_finder, low_context_name_finder

In [2]:
# Define pathings
data_path = '../01_data/'
out_path = '../03_output/'

In [3]:
#Load data
verbs_df = pl.read_csv(data_path + 'DS1 verbs in -th.csv', separator= ',' )

verbs_df.head()

shape: (5, 3)
┌─────────────────────────────────┬──────────┬─────────────────────────────────┐
│ Left                            ┆ KWIC     ┆ Right                           │
│ ---                             ┆ ---      ┆ ---                             │
│ str                             ┆ str      ┆ str                             │
╞═════════════════════════════════╪══════════╪═════════════════════════════════╡
│ of the forest graves. </s><s> … ┆ weareth  ┆ that ring, it allows for thine… │
│ ''d, forsooth speak to me once… ┆ hath     ┆ spoken of thee. </s><s> I like… │
│ first set upon thee. </s><s> H… ┆ clingeth ┆ to Shiva like some shadow...en… │
│ <s> Still I feel that boy hide… ┆ doth     ┆ bode most badly. </s><s> No re… │
│ , plunge down from the plank, … ┆ seeketh  ┆ thee? </s><s> Why could thou n… │
└─────────────────────────────────┴──────────┴─────────────────────────────────┘

In [4]:
#Load Character master table
char_master_df = pl.read_csv(data_path + 'das_char_master.csv')\
                   .with_columns(pl.col('Character').str.replace(',','').alias('Character'))

char_master_df.head()

shape: (5, 3)
┌─────────────────────────────┬───────┬───────┐
│ Character                   ┆ Class ┆ Age   │
│ ---                         ┆ ---   ┆ ---   │
│ str                         ┆ str   ┆ str   │
╞═════════════════════════════╪═══════╪═══════╡
│ ALVINA OF THE DARKROOT WOOD ┆ High  ┆ Old   │
│ ANASTACIA OF ASTORA         ┆ Low   ┆ Young │
│ ANDRE OF ASTORA             ┆ Low   ┆ Old   │
│ BIG HAТ LOGAN               ┆ Low   ┆ Old   │
│ BLACKSMITH VAMOS            ┆ Low   ┆ Old   │
└─────────────────────────────┴───────┴───────┘

In [5]:
#Instantiate list with missing verbs
missing_verbs = ['Cometh','Taketh','Returneth','Hunteth','Trespasseth','Commenceth','Reneweth','Obscureth','Endeth','Serveth','Maketh',
                 'cometh','taketh','returneth','hunteth','trespasseth','commenceth','reneweth','obscureth','endeth','serveth','maketh']

unneeded_verbs = ['Bequeath','bequeath']

In [6]:
# Open raw text to look for missing verbs
with open(data_path + 'Ds corpus input.txt', 'r', encoding='utf-8') as file:
        raw_text = file.read()  # Read the entire content into a single string
        # print(raw_text)

In [7]:
#Construct empty dataframe to input results
left_context = []
verbs = []
right_context = []
#Search for not found verbs
for missing in missing_verbs:
    idx = 0
    context_list = raw_text.split(missing)
    while idx + 1 < len(context_list):
        left_context.append(context_list[idx])
        verbs.append(missing)
        right_context.append(context_list[idx + 1][:300])
        idx += 1

# Construct dataframe with the found verbs and contexts, enrich with character name and format contexts to facilitate legibility
missing_verbs_df = pl.DataFrame().with_columns(pl.Series(left_context).alias('Left'),
                                                 pl.Series(verbs).alias('KWIC'),
                                                 pl.Series(right_context).alias('Right'))\
                     .with_columns(pl.col('Left').map_elements(name_finder, return_dtype=pl.Utf8).alias('Character'))\
                     .with_columns(pl.col('Left').str.replace_all('<s>','').str.replace_all('</s>',''),
                                   pl.col('Right').str.replace_all('<s>','').str.replace_all('</s>',''))\
                     .with_columns(pl.col('KWIC').str.to_lowercase().alias('KWIC'))\
                     .with_columns(pl.col('Character').forward_fill().alias('Character'))

missing_verbs_df

shape: (24, 4)
┌────────────────────────────────┬─────────┬───────────────────────────────┬───────────────────────┐
│ Left                           ┆ KWIC    ┆ Right                         ┆ Character             │
│ ---                            ┆ ---     ┆ ---                           ┆ ---                   │
│ str                            ┆ str     ┆ str                           ┆ str                   │
╞════════════════════════════════╪═════════╪═══════════════════════════════╪═══════════════════════╡
│ NARRATOR                       ┆ cometh  ┆  soon.                        ┆ GIANT BLACKSMITH      │
│ Yes, indeed. The Dark…         ┆         ┆                               ┆                       │
│  soon.                         ┆ cometh  ┆ soon. Mng. What's that?       ┆ GIANT BLACKSMITH      │
│                                ┆         ┆ Shiny…                        ┆                       │
│ soon. Mng. What's that? Shiny… ┆ cometh  ┆ thou to confess? Or to        ┆ OSWALD OF CARIM       │
│                                ┆         ┆ accuse…                       ┆                       │
│ thou to confess? Or to accuse… ┆ cometh  ┆  thou to                      ┆ OSWALD OF CARIM       │
│                                ┆         ┆ confess? Or to aсcuse…        ┆                       │
│ NARRATOR                       ┆ hunteth ┆ the enemies of the Lords, by  ┆ DARK SUN GWYNDOLIN    │
│ Yes, indeed. The Dark…         ┆         ┆ …                             ┆                       │
│ …                              ┆ …       ┆ …                             ┆ …                     │
│ NARRATOR                       ┆ endeth  ┆ the Godmother, and now thou   ┆ DARK SUN GWYNDOLIN    │
│ Yes, indeed. The Dark…         ┆         ┆ s…                            ┆                       │
│ the Godmother, and now thou s… ┆ endeth  ┆  this eternal                 ┆ GWYNEVERE PRINCESS OF │
│                                ┆         ┆ twilight, and av…             ┆ SUNLIGHT              │
│  this eternal                  ┆ endeth  ┆ this eternal twilight, and    ┆ GWYNEVERE PRINCESS OF │
│ twilight, and av…              ┆         ┆ av…                           ┆ SUNLIGHT              │
│ NARRATOR                       ┆ serveth ┆  as thine                     ┆ GWYNEVERE PRINCESS OF │
│ Yes, indeed. The Dark…         ┆         ┆ guardian. If thou so…         ┆ SUNLIGHT              │
│ NARRATOR                       ┆ maketh  ┆ pilgrimage to the land of     ┆ OSCAR OF ASTORA       │
│ Yes, indeed. The Dark…         ┆         ┆ Anc…                          ┆                       │
└────────────────────────────────┴─────────┴───────────────────────────────┴───────────────────────┘

In [8]:
missing_verbs_df.filter(pl.col('Character').is_null())

shape: (0, 4)
┌──────┬──────┬───────┬───────────┐
│ Left ┆ KWIC ┆ Right ┆ Character │
│ ---  ┆ ---  ┆ ---   ┆ ---       │
│ str  ┆ str  ┆ str   ┆ str       │
╞══════╪══════╪═══════╪═══════════╡
└──────┴──────┴───────┴───────────┘

In [9]:
# Clean the raw text to facilitate matching with low_context_name_finder
punctuation = [',','.',';',':','!','?']

raw_text_clean = raw_text.replace('\n',' ').replace('…','...').replace('‘',"'").replace("' ","'").strip()
for punct in punctuation:
        raw_text_clean = raw_text_clean.replace(punct, punct + ' ').replace(punct,'')

raw_text_clean = raw_text_clean.split(' ')

raw_text_clean = [word for word in raw_text_clean if word != '']

raw_text_clean = ' '.join(raw_text_clean)

# raw_text_clean

In [10]:
# Extract the speaking character for each row, turn all KWIC lowercase to avoid redundant values.
verbs_df = verbs_df.filter(~pl.col('KWIC').is_in(missing_verbs)).filter(~pl.col('KWIC').is_in(unneeded_verbs))\
                   .with_columns(pl.col('Left').map_elements(lambda x: low_context_name_finder(x, raw_text_clean, 50), 
                                                             return_dtype=pl.Utf8).alias('Character'))\
                         .with_columns(pl.col('KWIC').str.to_lowercase().alias('KWIC'))\
                         .with_columns(pl.col('Left').str.replace_all('<s>','').str.replace_all('</s>','\n'),
                                       pl.col('Right').str.replace_all('<s>','').str.replace_all('</s>','\n'))\
                         

# Concat with the missing verbs and trim contexts to facilitate legibility.
verbs_df = pl.concat([verbs_df, missing_verbs_df])\
             .with_columns(pl.col('Left').str.tail(300).alias('Left'),
                           pl.col('Right').str.head(300).alias('Right'))

verbs_df

shape: (46, 4)
┌───────────────────────────────┬──────────┬──────────────────────────────┬────────────────────────┐
│ Left                          ┆ KWIC     ┆ Right                        ┆ Character              │
│ ---                           ┆ ---      ┆ ---                          ┆ ---                    │
│ str                           ┆ str      ┆ str                          ┆ str                    │
╞═══════════════════════════════╪══════════╪══════════════════════════════╪════════════════════════╡
│ ould suit thee well.          ┆ weareth  ┆ that ring, it allows for     ┆ ALVINA OF THE DARKROOT │
│  Hmm, I …                     ┆          ┆ thine…                       ┆ WOOD                   │
│  once more and will join us?  ┆ hath     ┆ spoken of thee.              ┆ ALVINA OF THE DARKROOT │
│ …                             ┆          ┆  I like that …               ┆ WOOD                   │
│ earn thee many more           ┆ clingeth ┆ to Shiva like some           ┆ ALVINA OF THE DARKROOT │
│ Perchance.…                   ┆          ┆ shadow...en…                 ┆ WOOD                   │
│ ll use us badly...            ┆ doth     ┆ bode most badly.             ┆ ALVINA OF THE DARKROOT │
│  Yet on gu…                   ┆          ┆  No rest wil…                ┆ WOOD                   │
│ shall be requited not.        ┆ seeketh  ┆ thee?                        ┆ CROSSBREED PRISCILLA   │
│  Thou …                       ┆          ┆  Why could thou not let…     ┆                        │
│ …                             ┆ …        ┆ …                            ┆ …                      │
│ he Darkmoon trespasseth upon  ┆ endeth   ┆ the Godmother, and now thou  ┆ DARK SUN GWYNDOLIN     │
│ t…                            ┆          ┆ s…                           ┆                        │
│ sen Undead. Come hither,      ┆ endeth   ┆  this eternal                ┆ GWYNEVERE PRINCESS OF  │
│ child…                        ┆          ┆ twilight, and av…            ┆ SUNLIGHT               │
│ ire of our world. A grave and ┆ endeth   ┆ this eternal twilight, and   ┆ GWYNEVERE PRINCESS OF  │
│ …                             ┆          ┆ av…                          ┆ SUNLIGHT               │
│ Fire, all shall be a frigid   ┆ serveth  ┆  as thine                    ┆ GWYNEVERE PRINCESS OF  │
│ an…                           ┆          ┆ guardian. If thou so…        ┆ SUNLIGHT               │
│ ish to ask something of       ┆ maketh   ┆ pilgrimage to the land of    ┆ OSCAR OF ASTORA        │
│ you...…                       ┆          ┆ Anc…                         ┆                        │
└───────────────────────────────┴──────────┴──────────────────────────────┴────────────────────────┘

In [11]:
verbs_df.filter(pl.col('Character').is_null())#['Left'].to_list()

shape: (0, 4)
┌──────┬──────┬───────┬───────────┐
│ Left ┆ KWIC ┆ Right ┆ Character │
│ ---  ┆ ---  ┆ ---   ┆ ---       │
│ str  ┆ str  ┆ str   ┆ str       │
╞══════╪══════╪═══════╪═══════════╡
└──────┴──────┴───────┴───────────┘

In [12]:
#Add character class and age information from master table
verbs_df = verbs_df.join(char_master_df, on='Character', how = 'left')

verbs_df

shape: (46, 6)
┌───────────────────────┬──────────┬───────────────────────┬───────────────────────┬───────┬───────┐
│ Left                  ┆ KWIC     ┆ Right                 ┆ Character             ┆ Class ┆ Age   │
│ ---                   ┆ ---      ┆ ---                   ┆ ---                   ┆ ---   ┆ ---   │
│ str                   ┆ str      ┆ str                   ┆ str                   ┆ str   ┆ str   │
╞═══════════════════════╪══════════╪═══════════════════════╪═══════════════════════╪═══════╪═══════╡
│ ould suit thee well.  ┆ weareth  ┆ that ring, it allows  ┆ ALVINA OF THE         ┆ High  ┆ Old   │
│  Hmm, I …             ┆          ┆ for thine…            ┆ DARKROOT WOOD         ┆       ┆       │
│ once more and will    ┆ hath     ┆ spoken of thee.       ┆ ALVINA OF THE         ┆ High  ┆ Old   │
│ join us?              ┆          ┆  I like that …        ┆ DARKROOT WOOD         ┆       ┆       │
│ …                     ┆          ┆                       ┆                       ┆       ┆       │
│ earn thee many more   ┆ clingeth ┆ to Shiva like some    ┆ ALVINA OF THE         ┆ High  ┆ Old   │
│ Perchance.…           ┆          ┆ shadow...en…          ┆ DARKROOT WOOD         ┆       ┆       │
│ ll use us badly...    ┆ doth     ┆ bode most badly.      ┆ ALVINA OF THE         ┆ High  ┆ Old   │
│  Yet on gu…           ┆          ┆  No rest wil…         ┆ DARKROOT WOOD         ┆       ┆       │
│ shall be requited     ┆ seeketh  ┆ thee?                 ┆ CROSSBREED PRISCILLA  ┆ High  ┆ Old   │
│ not.                  ┆          ┆ Why could thou not    ┆                       ┆       ┆       │
│  Thou …               ┆          ┆ let…                  ┆                       ┆       ┆       │
│ …                     ┆ …        ┆ …                     ┆ …                     ┆ …     ┆ …     │
│ he Darkmoon           ┆ endeth   ┆ the Godmother, and    ┆ DARK SUN GWYNDOLIN    ┆ High  ┆ Old   │
│ trespasseth upon t…   ┆          ┆ now thou s…           ┆                       ┆       ┆       │
│ sen Undead. Come      ┆ endeth   ┆  this eternal         ┆ GWYNEVERE PRINCESS OF ┆ High  ┆ Old   │
│ hither, child…        ┆          ┆ twilight, and av…     ┆ SUNLIGHT              ┆       ┆       │
│ ire of our world. A   ┆ endeth   ┆ this eternal          ┆ GWYNEVERE PRINCESS OF ┆ High  ┆ Old   │
│ grave and …           ┆          ┆ twilight, and av…     ┆ SUNLIGHT              ┆       ┆       │
│ Fire, all shall be a  ┆ serveth  ┆  as thine             ┆ GWYNEVERE PRINCESS OF ┆ High  ┆ Old   │
│ frigid an…            ┆          ┆ guardian. If thou so… ┆ SUNLIGHT              ┆       ┆       │
│ ish to ask something  ┆ maketh   ┆ pilgrimage to the     ┆ OSCAR OF ASTORA       ┆ Low   ┆ Young │
│ of you...…            ┆          ┆ land of Anc…          ┆                       ┆       ┆       │
└───────────────────────┴──────────┴───────────────────────┴───────────────────────┴───────┴───────┘

In [13]:
verbs_df.filter(pl.col('Character').is_null())

shape: (0, 6)
┌──────┬──────┬───────┬───────────┬───────┬─────┐
│ Left ┆ KWIC ┆ Right ┆ Character ┆ Class ┆ Age │
│ ---  ┆ ---  ┆ ---   ┆ ---       ┆ ---   ┆ --- │
│ str  ┆ str  ┆ str   ┆ str       ┆ str   ┆ str │
╞══════╪══════╪═══════╪═══════════╪═══════╪═════╡
└──────┴──────┴───────┴───────────┴───────┴─────┘

In [14]:
# Sanity check for extracted characters
verbs_df.to_pandas()['Character'].unique()

array(['ALVINA OF THE DARKROOT WOOD', 'CROSSBREED PRISCILLA',
       'DARK SUN GWYNDOLIN', 'DARKSTALKER KAATHЕ', 'DUSK OF OOLACILE',
       'GIANT BLACKSMITH', 'GWYNEVERE PRINCESS OF SUNLIGHT',
       'HAWKEYE GOUGН', 'OSCAR OF ASTORA', 'OSWALD OF CARIM'],
      dtype=object)

In [16]:
# Save enriched dataframe into a csv file.
verbs_df.write_csv(out_path + 'th_verbs_analysis.csv', separator= ';')