In [ ]:
import polars as pl
import pandas as pd

import sys
sys.path.append('../../04_utils')

from utils import name_finder, low_context_name_finder

In [ ]:
# Define pathings
data_path = '../../01_data/'
out_path = '../../03_output/01_enriched_results/'

In [3]:
#Load data
pronouns_df = pl.read_csv(data_path + 'das_tfg_pronoun_study.csv', separator= ',' )

pronouns_df.head()

shape: (5, 3)
┌─────────────────────────────────┬──────┬─────────────────────────────────┐
│ Left                            ┆ KWIC ┆ Right                           │
│ ---                             ┆ ---  ┆ ---                             │
│ str                             ┆ str  ┆ str                             │
╞═════════════════════════════════╪══════╪═════════════════════════════════╡
│ <s> NARRATOR Yes, indeed. </s>… ┆ they ┆ are locked away, to await the … │
│ <s> NARRATOR Yes, indeed. </s>… ┆ your ┆ fate. </s><s> Only, in the anc… │
│ <s> NARRATOR Yes, indeed. </s>… ┆ it   ┆ is stated, that one day an Und… │
│ brands the Undead. </s><s> And… ┆ it   ┆ not so that thou art new. </s>… │
│ the Undead. </s><s> And in thi… ┆ thou ┆ art new. </s><s> Thou fared we… │
└─────────────────────────────────┴──────┴─────────────────────────────────┘

In [4]:
#Load Character master table
char_master_df = pl.read_csv(data_path + 'das_char_master.csv')\
                   .with_columns(pl.col('Character').str.replace(',','').alias('Character'))

char_master_df.head()

shape: (5, 3)
┌─────────────────────────────┬───────┬───────┐
│ Character                   ┆ Class ┆ Age   │
│ ---                         ┆ ---   ┆ ---   │
│ str                         ┆ str   ┆ str   │
╞═════════════════════════════╪═══════╪═══════╡
│ ALVINA OF THE DARKROOT WOOD ┆ High  ┆ Old   │
│ ANASTACIA OF ASTORA         ┆ Low   ┆ Young │
│ ANDRE OF ASTORA             ┆ Low   ┆ Old   │
│ BIG HAТ LOGAN               ┆ Low   ┆ Old   │
│ BLACKSMITH VAMOS            ┆ Low   ┆ Old   │
└─────────────────────────────┴───────┴───────┘

In [5]:
#Instantiate list with missing pronouns
missing_pronouns = ['mine', 'mineself',
                    'Mine', 'Mineself']

In [6]:
# Open raw text to look for missing pronouns
with open(data_path + 'Ds corpus input.txt', 'r', encoding='utf-8') as file:
        raw_text = file.read()  # Read the entire content into a single string
        # print(raw_text)

In [7]:
#Construct empty dataframe to input results
left_context = []
pronouns = []
right_context = []
#Search for not found pronouns
for missing in missing_pronouns:
    idx = 0
    context_list = raw_text.split(missing)
    while idx + 1 < len(context_list):
        left_context.append(context_list[idx])
        pronouns.append(missing)
        right_context.append(context_list[idx + 1][:300])
        idx += 1

# Construct dataframe with the found pronouns and contexts, enrich with character name and format contexts to facilitate legibility
missing_pronouns_df = pl.DataFrame().with_columns(pl.Series(left_context).alias('Left'),
                                                 pl.Series(pronouns).alias('KWIC'),
                                                 pl.Series(right_context).alias('Right'))\
                     .with_columns(pl.col('Left').map_elements(name_finder, return_dtype=pl.Utf8).alias('Character'))\
                     .with_columns(pl.col('Left').str.replace_all('<s>','').str.replace_all('</s>',''),
                                   pl.col('Right').str.replace_all('<s>','').str.replace_all('</s>',''))\
                     .with_columns(pl.col('KWIC').str.to_lowercase().alias('KWIC'))\
                     .with_columns(pl.col('Character').forward_fill().alias('Character'))

missing_pronouns_df

shape: (20, 4)
┌───────────────────────────────┬──────────┬──────────────────────────────┬────────────────────────┐
│ Left                          ┆ KWIC     ┆ Right                        ┆ Character              │
│ ---                           ┆ ---      ┆ ---                          ┆ ---                    │
│ str                           ┆ str      ┆ str                          ┆ str                    │
╞═══════════════════════════════╪══════════╪══════════════════════════════╪════════════════════════╡
│ NARRATOR                      ┆ mine     ┆  senses reveal intruders,    ┆ ALVINA OF THE DARKROOT │
│ Yes, indeed. The Dark…        ┆          ┆ then…                        ┆ WOOD                   │
│  senses reveal intruders,     ┆ mine     ┆ eyes first set upon thee.    ┆ ALVINA OF THE DARKROOT │
│ then…                         ┆          ┆ Her…                         ┆ WOOD                   │
│ eyes first set upon thee.     ┆ mine     ┆ is yours, but at a price!    ┆ CRESTFALLEN MERCHANT   │
│ Her…                          ┆          ┆ Not…                         ┆                        │
│ is yours, but at a price!     ┆ mine     ┆ d. They practically queue to ┆ CRESTFALLEN WARRIOR    │
│ Not…                          ┆          ┆ e…                           ┆                        │
│ d. They practically queue to  ┆ mine     ┆ self,                        ┆ DARK SUN GWYNDOLIN     │
│ e…                            ┆          ┆ Gwyndolin, and kneel bef…    ┆                        │
│ …                             ┆ …        ┆ …                            ┆ …                      │
│ ? Thank goodness! I knew he   ┆ mine     ┆ will remain in contact. But, ┆ SOLAIRE OF ASTORA      │
│ wa…                           ┆          ┆ …                            ┆                        │
│ NARRATOR                      ┆ mineself ┆ ,                            ┆ DARK SUN GWYNDOLIN     │
│ Yes, indeed. The Dark…        ┆          ┆ Gwyndolin, and kneel before  ┆                        │
│                               ┆          ┆ …                            ┆                        │
│ ,                             ┆ mineself ┆ , Gwyndolin! Thou shalt not  ┆ DARK SUN GWYNDOLIN     │
│ Gwyndolin, and kneel before … ┆          ┆ go…                          ┆                        │
│ , Gwyndolin! Thou shalt not   ┆ mineself ┆ , Gwyndolin! Thou shalt not  ┆ DARK SUN GWYNDOLIN     │
│ go…                           ┆          ┆ go…                          ┆                        │
│ , Gwyndolin! Thou shalt not   ┆ mineself ┆ , Gwyndolin! Thou shalt not  ┆ DARK SUN GWYNDOLIN     │
│ go…                           ┆          ┆ go…                          ┆                        │
└───────────────────────────────┴──────────┴──────────────────────────────┴────────────────────────┘

In [8]:
missing_pronouns_df.filter(pl.col('Character').is_null())

shape: (0, 4)
┌──────┬──────┬───────┬───────────┐
│ Left ┆ KWIC ┆ Right ┆ Character │
│ ---  ┆ ---  ┆ ---   ┆ ---       │
│ str  ┆ str  ┆ str   ┆ str       │
╞══════╪══════╪═══════╪═══════════╡
└──────┴──────┴───────┴───────────┘

In [9]:
# Extract the speaking character for each row, turn all KWIC lowercase to avoid redundant values
pronouns_df = pronouns_df.with_columns(pl.col('Left').map_elements(name_finder, return_dtype=pl.Utf8).alias('Character'))\
                         .with_columns(pl.col('KWIC').str.to_lowercase().alias('KWIC'))\
                         .with_columns(pl.col('Character').forward_fill().alias('Character'))\
                         .with_columns(pl.col('Left').str.replace_all('<s>','').str.replace_all('</s>','\n'),
                                       pl.col('Right').str.replace_all('<s>','').str.replace_all('</s>','\n'))\

# Concat with the missing pronouns and trim contexts to facilitate legibility.
pronouns_df = pl.concat([pronouns_df, missing_pronouns_df])\
             .with_columns(pl.col('Left').str.tail(300).alias('Left'),
                           pl.col('Right').str.head(300).alias('Right'))

pronouns_df

shape: (3_479, 4)
┌───────────────────────────────┬──────────┬──────────────────────────────┬────────────────────────┐
│ Left                          ┆ KWIC     ┆ Right                        ┆ Character              │
│ ---                           ┆ ---      ┆ ---                          ┆ ---                    │
│ str                           ┆ str      ┆ str                          ┆ str                    │
╞═══════════════════════════════╪══════════╪══════════════════════════════╪════════════════════════╡
│  NARRATOR Yes, indeed.        ┆ they     ┆ are locked away, to await    ┆ NARRATOR               │
│  The D…                       ┆          ┆ the …                        ┆                        │
│  NARRATOR Yes, indeed.        ┆ your     ┆ fate.                        ┆ NARRATOR               │
│  The D…                       ┆          ┆  Only, in the ancient l…     ┆                        │
│  NARRATOR Yes, indeed.        ┆ it       ┆ is stated, that one day an   ┆ NARRATOR               │
│  The D…                       ┆          ┆ Und…                         ┆                        │
│ ed to the north, where they   ┆ it       ┆ not so that thou art new.    ┆ ALVINA OF THE DARKROOT │
│ ar…                           ┆          ┆  Th…                         ┆ WOOD                   │
│ , where they are locked away, ┆ thou     ┆ art new.                     ┆ ALVINA OF THE DARKROOT │
│ …                             ┆          ┆  Thou fared well to …        ┆ WOOD                   │
│ …                             ┆ …        ┆ …                            ┆ …                      │
│ ly journey? This pleases me   ┆ mine     ┆ will remain in contact. But, ┆ SOLAIRE OF ASTORA      │
│ gr…                           ┆          ┆ …                            ┆                        │
│ What seeketh thee? Why could  ┆ mineself ┆ ,                            ┆ DARK SUN GWYNDOLIN     │
│ t…                            ┆          ┆ Gwyndolin, and kneel before  ┆                        │
│                               ┆          ┆ …                            ┆                        │
│ ,                             ┆ mineself ┆ , Gwyndolin! Thou shalt not  ┆ DARK SUN GWYNDOLIN     │
│ Gwyndolin, and kneel before … ┆          ┆ go…                          ┆                        │
│ ishness… Why                  ┆ mineself ┆ , Gwyndolin! Thou shalt not  ┆ DARK SUN GWYNDOLIN     │
│ trespasseth upon …            ┆          ┆ go…                          ┆                        │
│ , Gwyndolin! Thou shalt not   ┆ mineself ┆ , Gwyndolin! Thou shalt not  ┆ DARK SUN GWYNDOLIN     │
│ go…                           ┆          ┆ go…                          ┆                        │
└───────────────────────────────┴──────────┴──────────────────────────────┴────────────────────────┘

In [10]:
#Add character class and age information from master table
pronouns_df = pronouns_df.join(char_master_df, on='Character', how = 'left')

pronouns_df

shape: (3_479, 6)
┌─────────────────────────┬──────────┬────────────────────────┬────────────────────┬───────┬───────┐
│ Left                    ┆ KWIC     ┆ Right                  ┆ Character          ┆ Class ┆ Age   │
│ ---                     ┆ ---      ┆ ---                    ┆ ---                ┆ ---   ┆ ---   │
│ str                     ┆ str      ┆ str                    ┆ str                ┆ str   ┆ str   │
╞═════════════════════════╪══════════╪════════════════════════╪════════════════════╪═══════╪═══════╡
│  NARRATOR Yes, indeed.  ┆ they     ┆ are locked away, to    ┆ NARRATOR           ┆ null  ┆ null  │
│  The D…                 ┆          ┆ await the …            ┆                    ┆       ┆       │
│  NARRATOR Yes, indeed.  ┆ your     ┆ fate.                  ┆ NARRATOR           ┆ null  ┆ null  │
│  The D…                 ┆          ┆ Only, in the ancient   ┆                    ┆       ┆       │
│                         ┆          ┆ l…                     ┆                    ┆       ┆       │
│  NARRATOR Yes, indeed.  ┆ it       ┆ is stated, that one    ┆ NARRATOR           ┆ null  ┆ null  │
│  The D…                 ┆          ┆ day an Und…            ┆                    ┆       ┆       │
│ ed to the north, where  ┆ it       ┆ not so that thou art   ┆ ALVINA OF THE      ┆ High  ┆ Old   │
│ they ar…                ┆          ┆ new.                   ┆ DARKROOT WOOD      ┆       ┆       │
│                         ┆          ┆  Th…                   ┆                    ┆       ┆       │
│ , where they are locked ┆ thou     ┆ art new.               ┆ ALVINA OF THE      ┆ High  ┆ Old   │
│ away, …                 ┆          ┆  Thou fared well to …  ┆ DARKROOT WOOD      ┆       ┆       │
│ …                       ┆ …        ┆ …                      ┆ …                  ┆ …     ┆ …     │
│ ly journey? This        ┆ mine     ┆ will remain in         ┆ SOLAIRE OF ASTORA  ┆ Low   ┆ Young │
│ pleases me gr…          ┆          ┆ contact. But, …        ┆                    ┆       ┆       │
│ What seeketh thee? Why  ┆ mineself ┆ ,                      ┆ DARK SUN GWYNDOLIN ┆ High  ┆ Old   │
│ could                   ┆          ┆ Gwyndolin, and kneel   ┆                    ┆       ┆       │
│ t…                      ┆          ┆ before …               ┆                    ┆       ┆       │
│ ,                       ┆ mineself ┆ , Gwyndolin! Thou      ┆ DARK SUN GWYNDOLIN ┆ High  ┆ Old   │
│ Gwyndolin, and kneel    ┆          ┆ shalt not go…          ┆                    ┆       ┆       │
│ before …                ┆          ┆                        ┆                    ┆       ┆       │
│ ishness… Why            ┆ mineself ┆ , Gwyndolin! Thou      ┆ DARK SUN GWYNDOLIN ┆ High  ┆ Old   │
│ trespasseth upon …      ┆          ┆ shalt not go…          ┆                    ┆       ┆       │
│ , Gwyndolin! Thou shalt ┆ mineself ┆ , Gwyndolin! Thou      ┆ DARK SUN GWYNDOLIN ┆ High  ┆ Old   │
│ not go…                 ┆          ┆ shalt not go…          ┆                    ┆       ┆       │
└─────────────────────────┴──────────┴────────────────────────┴────────────────────┴───────┴───────┘

In [11]:
pronouns_df.filter(pl.col('Character').is_null())

shape: (0, 6)
┌──────┬──────┬───────┬───────────┬───────┬─────┐
│ Left ┆ KWIC ┆ Right ┆ Character ┆ Class ┆ Age │
│ ---  ┆ ---  ┆ ---   ┆ ---       ┆ ---   ┆ --- │
│ str  ┆ str  ┆ str   ┆ str       ┆ str   ┆ str │
╞══════╪══════╪═══════╪═══════════╪═══════╪═════╡
└──────┴──────┴───────┴───────────┴───────┴─────┘

In [12]:
# Sanity check for extracted characters
pronouns_df.to_pandas()['Character'].unique()

array(['NARRATOR', 'ALVINA OF THE DARKROOT WOOD', 'ANASTACIA OF ASTORA',
       'ANDRE OF ASTORA', 'BIG HAТ LOGAN', 'BLACKSMITH VAMOS',
       'CRESTFALLEN MERCHANT', 'CRESTFALLEN WARRIOR',
       'CROSSBREED PRISCILLA', 'DARK SUN GWYNDOLIN', 'DARKMOON KNIGHTESS',
       'DARKSTALKER KAATHЕ', 'DOMHNALL OF ZENA', 'DUSK OF OOLACILE',
       'EINGYI OF THE GREAT SWAMP', 'ELIZABETH KEEPER OF THE SANCTUARY',
       'GIANT BLACKSMITH', 'GRIGGS OF VINHEIM',
       'GWYNEVERE PRINCESS OF SUNLIGHT', 'HAWKEYE GOUGН',
       'INGWARD KEEPER OF THE SEAL', 'KINGSEEKER FRAMPТ',
       'LAURENTIUS OF THЕ GREAT SWAMP', 'LAUTREC OF CARIM',
       "LORD''S BLADE CIARAN", 'MARVELOUS CHESTER', 'OSCAR OF ASTORA',
       'OSWALD OF CARIM', 'PETRUS OF THOROLUND', 'QUELANA OF IZALITH',
       'RHEA OF THOROLUND', 'RICKERT OF VINHEIM', 'SHIVA OF THE EAST',
       'SIEGLINDE OF CATARINA', 'SIEGMEYER OF CATARINA', 'HAWK GIRL',
       'SOLAIRE OF ASTORA', 'THE FAIR LADY', 'TRUSTY PATCHES',
       'UNDEAD MERCHANT (FEMALE)', 'UNDEAD MERCHANT (MALE)',
       'VINCE OF THOROLUND'], dtype=object)

In [13]:
# Save enriched dataframe into a csv file.
pronouns_df.write_csv(out_path + 'pronoun_analysis.csv', separator= ';')